#!/bin/bash

# FHEVM Examples Generator - Verification Script
# This script verifies all deliverables and functionality

echo "=========================================="
echo "FHEVM Examples Generator - Verification"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Track results
PASSED=0
FAILED=0

# Function to check if a file exists
check_file() {
    if [ -f "$1" ]; then
        echo -e "${GREEN}✓${NC} $1 exists"
        ((PASSED++))
    else
        echo -e "${RED}✗${NC} $1 missing"
        ((FAILED++))
    fi
}

# Function to check if a directory exists
check_dir() {
    if [ -d "$1" ]; then
        echo -e "${GREEN}✓${NC} $1 exists"
        ((PASSED++))
    else
        echo -e "${RED}✗${NC} $1 missing"
        ((FAILED++))
    fi
}

# Function to run a command and check exit code
run_check() {
    local desc="$1"
    shift
    if "$@" > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} $desc"
        ((PASSED++))
    else
        echo -e "${RED}✗${NC} $desc"
        ((FAILED++))
    fi
}

echo "1. Checking Core Files..."
echo "----------------------------"
check_file "package.json"
check_file "tsconfig.json"
check_file "jest.config.js"
check_file "README.md"
check_file "SUBMISSION.md"
check_file "demo-script.md"
check_file "record-demo.sh"
echo ""

echo "2. Checking Source Files..."
echo "----------------------------"
check_file "src/cli/create-fhevm-example.ts"
check_file "src/docgen/generate-docs.ts"
check_file "scripts/scaffold-all.ts"
check_file ".github/workflows/ci.yml"
check_file "__tests__/generator.test.ts"
echo ""

echo "3. Checking Templates..."
echo "----------------------------"
check_file "templates/contracts/basic-counter.sol"
check_file "templates/contracts/arithmetic.sol"
check_file "templates/tests/basic-counter.test.ts"
check_file "templates/tests/arithmetic.test.ts"
echo ""

echo "4. Checking Base Template..."
echo "----------------------------"
check_dir "base-template"
check_file "base-template/package.json"
check_file "base-template/contracts/FHECounter.sol"
echo ""

echo "5. Checking Node/NPM..."
echo "----------------------------"
run_check "Node.js installed" node --version
run_check "NPM installed" npm --version
run_check "Git installed" git --version
echo ""

echo "6. Checking Dependencies..."
echo "----------------------------"
if [ -d "node_modules" ]; then
    echo -e "${GREEN}✓${NC} node_modules exists"
    ((PASSED++))
else
    echo -e "${YELLOW}⚠${NC} node_modules missing - run 'npm ci'"
fi
echo ""

echo "7. Checking Scaffolded Examples..."
echo "----------------------------"
if [ -d "scaffolded" ]; then
    check_dir "scaffolded/basic-counter"
    check_dir "scaffolded/arithmetic"

    if [ -d "scaffolded/basic-counter" ]; then
        check_file "scaffolded/basic-counter/README.md"
        check_file "scaffolded/basic-counter/contracts/basic-counter.sol"
        check_file "scaffolded/basic-counter/test/basic-counter.test.ts"

        # Check git history
        cd scaffolded/basic-counter
        if git log --oneline -n 1 | grep -q "docs: add autogenerated README"; then
            echo -e "${GREEN}✓${NC} Git history preserved"
            ((PASSED++))
        else
            echo -e "${RED}✗${NC} Git history not preserved"
            ((FAILED++))
        fi

        # Check branch
        if git branch | grep -q "fhevm-example/basic-counter"; then
            echo -e "${GREEN}✓${NC} Dedicated branch created"
            ((PASSED++))
        else
            echo -e "${RED}✗${NC} Dedicated branch missing"
            ((FAILED++))
        fi

        # Check remote
        if git remote -v | grep -q "your-origin"; then
            echo -e "${GREEN}✓${NC} Placeholder remote configured"
            ((PASSED++))
        else
            echo -e "${RED}✗${NC} Placeholder remote missing"
            ((FAILED++))
        fi

        cd ../..
    fi
else
    echo -e "${YELLOW}⚠${NC} scaffolded/ directory missing - run 'npm run scaffold:all'"
fi
echo ""

echo "8. Checking Deliverables..."
echo "----------------------------"
if [ -f "deliverables.json" ]; then
    check_file "deliverables.json"

    # Check if deliverables.json has entries
    if grep -q "basic-counter" deliverables.json; then
        echo -e "${GREEN}✓${NC} deliverables.json has basic-counter"
        ((PASSED++))
    else
        echo -e "${RED}✗${NC} deliverables.json missing basic-counter"
        ((FAILED++))
    fi

    if grep -q "arithmetic" deliverables.json; then
        echo -e "${GREEN}✓${NC} deliverables.json has arithmetic"
        ((PASSED++))
    else
        echo -e "${RED}✗${NC} deliverables.json missing arithmetic"
        ((FAILED++))
    fi
else
    echo -e "${YELLOW}⚠${NC} deliverables.json missing - run 'npm run scaffold:all'"
fi

check_file "summary.txt"
echo ""

echo "=========================================="
echo "Verification Summary"
echo "=========================================="
echo -e "${GREEN}Passed: $PASSED${NC}"
echo -e "${RED}Failed: $FAILED${NC}"
echo ""

if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}✓ All checks passed!${NC}"
    echo ""
    echo "Next steps:"
    echo "1. Run 'npm ci' if you haven't already"
    echo "2. Run 'npm test' to test the generator"
    echo "3. Run 'npm run scaffold:all' to scaffold all examples"
    echo "4. Review deliverables.json and summary.txt"
    echo "5. Push scaffolded examples to GitHub"
    exit 0
else
    echo -e "${RED}✗ Some checks failed${NC}"
    echo ""
    echo "Please review the errors above and:"
    echo "1. Ensure all files are present"
    echo "2. Run 'npm ci' to install dependencies"
    echo "3. Run 'npm run scaffold:all' to generate examples"
    exit 1
fi
